version: 2.1

commands:
  extract-tag-semver:
    steps:
      - run: which python
      - run:
          name: Retrieve semver version from git tag
          command: |
            echo "git tag: ${CIRCLE_TAG}"
            export SEMVER_VERSION=$(python -c 'import os; import re; tag = os.environ.get("CIRCLE_TAG"); pattern = re.compile("^(.+-)?(?P<version>\d+\.\d+\.\d)(-.+)?$"); r = pattern.match(tag); print(r.group("version"))')
            echo "Semver version: ${SEMVER_VERSION}"
            # save to $BASH_ENV
            echo "export SEM_VERSION=$SEMVER_VERSION" >> $BASH_ENV
      - run: printenv SEM_VERSION
jobs:
  build:
    docker:
      - image: cimg/python:3.9.0
    resource_class: small
    parameters:
      branch:
        type: string
    steps:
      - run: |
          echo "args, branch: << parameters.branch >>"
  on-tag:
    docker:
      - image: cimg/python:3.9.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: "[optional] look up commit SHA from git tag"
          command: git rev-list -n 1 $CIRCLE_TAG
      - run:
          name: look up branches from commit SHA
          command: git --no-pager branch -a --contains $CIRCLE_SHA1
      - extract-tag-semver


workflows:
  main:
    jobs:
      - on-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
