version: 2.1

commands:
  details:
    steps:
      - run: 
          name: show details
          command: |
            echo "Hello from ${CIRCLE_JOB}"
            echo "Found: Git tag ${CIRCLE_TAG}"
            echo "Found: Git branch ${CIRCLE_BRANCH}"
            echo "Git commit ${CIRCLE_SHA1}"

executors:
  basic:
    docker:
      - image: cimg/base:current
    resource_class: small

jobs:
  aaa:
    executor: basic
    steps:
      - details
  bbb:
    executor: basic
    steps:
      - details
  last:
    executor: basic
    steps:
      - run: echo "DONE"

workflows:
  tag-only:
    jobs:
      - aaa:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - last:
          requires:
            - aaa
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  tag-mixed:
    jobs:
      - aaa:
          filters:
            tags:
              only: /^v.*/
      - bbb:
          requires:
            - aaa
      - last:
          requires:
            - bbb
            - aaa
          filters:
            tags:
              only: /^v.*/
  always:
    jobs:
      - aaa
      - last:
          requires:
            - aaa
