version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.0
    resource_class: small
    parameters:
      branch:
        type: string
    steps:
      - run: |
          echo "args, branch: << parameters.branch >>"
  on-tag:
    docker:
      - image: cimg/python:3.9.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: print git tag
          command: echo "Tagged: ${CIRCLE_TAG}"
      - run:
          name: "[optional] look up commit SHA from git tag"
          command: git rev-list -n 1 $CIRCLE_TAG
      - run:
          name: look up branches from commit SHA
          command: git --no-pager branch -a --contains $CIRCLE_SHA1


workflows:
  main:
    jobs:
      - on-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
