version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.0
    resource_class: small
    parameters:
      branch:
        type: string
    steps:
      - run: |
          echo "args, branch: << parameters.branch >>"
  on-tag:
    docker:
      - image: cimg/python:3.9.0
    resource_class: small
    steps:
      - run: |
          echo "Tagged: ${CIRCLE_TAG}"


workflows:
  main:
    when:
      not: << pipeline.git.tag >> 
    jobs:
      - build:
          branch: <<pipeline.git.branch>>
  on-tag:
    when: << pipeline.git.tag >> 
    jobs:
      - on-tag:
          filters:
            tags:
              only: /.*/
