version: 2.1

jobs:
  on-tag:
    docker:
      - image: cimg/python:3.9.0
    resource_class: small
    parameters:
      tag:
        type: string
    steps:
      - run: |
          echo "args, branch: << parameters.tag >>"
  build:
    docker:
      - image: cimg/python:3.9.0
    resource_class: small
    steps:
      - run: |
          echo "commit: ${CIRCLE_SHA1}"


workflows:
  main:
    jobs:
      - on-tag:
          branch: <<pipeline.git.tag>>
          filters:
            tags:
              only: /.*/
